### ISSUE TITLE
Disconnect from Nut server when 'On Battery'

### ISSUE THREAD

**Issue by ChrisBCH** [gawindx/WinNUT-Client#133]
I have the same issue again with V2.0.7722.30975: WinNut disconnect from NUT server when switching on battery. This issue was closed but I think it is still open.

**Comment by Pete1979** [comment]
I have this issue as well.

**Comment by SHC22** [comment]
I have the same problem.

**Comment by MADXhh** [comment]
Same here!

**Comment by gbakeman** [comment]
Everyone, please see the above issue on the nutdotnet repository. This was fixed in a [pre-release](https://github.com/nutdotnet/WinNUT-Client/releases). @ChrisBCH , please close this issue so other people will know to go to the one linked above.

**Comment by ChrisBCH** [comment]
fixed in a [pre-release](https://github.com/nutdotnet/WinNUT-Client/releases).
