### ISSUE TITLE
Wi-fi support

### ISSUE THREAD

**Issue by asitnik** [gawindx/WinNUT-Client#14]
Greetings,
I'd like to have the client connect to the server via wi-fi, and it doesn't work; it requires an Ethernet connection. Can that be done? Thanks.

**Comment by gawindx** [comment]
I am quite surprised by your problem.
The connection is made via IP, and therefore it has nothing to do with wi-fi (unless it has to do with your question about IPV6).

**Comment by gawindx** [comment]
Keep me informed if the addition of IPV6 support solved your WiFi problem or if it is still current.

While waiting for your return, I leave this issue open.

**Comment by asitnik** [comment]
It looks good, thanks. Version 1.8 looks awesome!

Ari Sitnik
justaskenterprises@gmail.com
Cell: 647-274-9665
LinkedIn: ca.linkedin.com/in/asitnik
Twitter: twitter.com/asitnik
Skype: asitnik <https://is.gd/qKKvAr>

**Comment by asitnik** [comment]
I've skipped over to 2.0.x and, so far, so good.

**Comment by gawindx** [comment]
I think that with V2, this problem is no longer relevant

I close the issue, it will have to be reopened if necessary
