### ISSUE TITLE
Increasing battery max in Calibration extends the gauge instead of adjusting scale.

### ISSUE THREAD

**Issue by hugalafutro** [gawindx/WinNUT-Client#150]
I hope the title makes sense. I am using version v2.1.7740.35837 on Windows 11 x64 as netclient for nut server running on pi4.

I increased the max to 28 as my charged battery sits at around 27.1 and expected the gauge to remain same size and the data on it to "shrink", instead the gauge grew a new notch triggering my imagined ocd how it's all uneven now.

I don't think the needle points at correct place either.

![image](https://user-images.githubusercontent.com/30209689/183285932-afcb1851-88fb-4be3-a07c-b6a61582daa6.png)

Otherwise everything seems to work ok, thanks for your work on this tool!

**Comment by gbakeman** [comment]
@hugalafutro We've moved the repository to a new location, would you mind duplicating this over at [nutdotnet/WinNUT-Client](https://github.com/nutdotnet/WinNUT-Client/issues/new/choose) and I'll take a look?

**Comment by hugalafutro** [comment]
done @ https://github.com/nutdotnet/WinNUT-Client/issues/18
