### ISSUE TITLE
Interval set to 0 with a fresh installation

### ISSUE THREAD

**Issue by mann1x** [gawindx/WinNUT-Client#154]
WinNUT v2.1.7740.35837

Interval is set to 0 in settings and if left as is will prevent WinNUT to start
I thought it meant something like auto, was not sure exactly about the exact meaning
Had to go to the registry and change the delay key to 1 

WinNUT Bug Report
Os Version : 6.2.9200.0
WinNUT Version : 2.1.7740.35837

WinNUT Parameters : 
{
  "Delay": 0,
  "AutoReconnect": "True",
  "MinInputVoltage": 210,
  "MaxInputVoltage": 270,
  "FrequencySupply": 0,
  "MinInputFrequency": 40,
  "MaxInputFrequency": 60,
  "MinOutputVoltage": 210,
  "MaxOutputVoltage": 250,
  "MinUPSLoad": 0,
  "MaxUPSLoad": 100,
  "MinBattVoltage": 6,
  "MaxBattVoltage": 18,
  "MinimizeToTray": "False",
  "MinimizeOnStart": "False",
  "CloseToTray": "False",
  "StartWithWindows": "False",
  "UseLogFile": "False",
  "Log Level": 0,
  "ShutdownLimitBatteryCharge": 30,
  "ShutdownLimitUPSRemainTime": 120,
  "ImmediateStopAction": "False",
  "Follow_FSD": "False",
  "TypeOfStop": 0,
  "DelayToShutdown": 15,
  "AllowExtendedShutdownDelay": "False",
  "ExtendedShutdownDelay": 15,
  "VerifyUpdate": "True",
  "VerifyUpdateAtStart": "True",
  "DelayBetweenEachVerification": 1,
  "StableOrDevBranch": 0,
  "LastDateVerification": ""
}

Error Message : 
Exception type: System.ArgumentOutOfRangeException
Exception message: Value '0' is not a valid value for Interval. Interval must be greater than 0.
Parameter name: Interval
Exception stack trace: 
   at System.Windows.Forms.Timer.set_Interval(Int32 value)
   at WinNUT_Client.WinNUT.WinNUT_Load(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Last Events :
26/08/2022 12:46:17 Pid: 49596 WinNUT : Initialisation Globals Variables Complete
26/08/2022 12:46:17 Pid: 49596 WinNUT : Initialisation Params Complete
26/08/2022 12:46:17 Pid: 49596 WinNUT : Loaded Params Complete
26/08/2022 12:46:17 Pid: 49596 WinNUT : NotifyIcons Initialised
26/08/2022 12:46:17 Pid: 49596 WinNUT : Windows 10 Toast Notification Not Available. Too Old Windows Version
26/08/2022 12:46:17 Pid: 49596 UPS_Device : TCP Socket Created
26/08/2022 12:46:17 Pid: 49596 UPS_Device : Enter GetUPSVar
26/08/2022 12:46:17 Pid: 49596 UPS_Device : Process Result With ups.mfr : VAR eaton ups.mfr "EATON"
26/08/2022 12:46:17 Pid: 49596 UPS_Device : Enter GetUPSVar
26/08/2022 12:46:17 Pid: 49596 UPS_Device : Process Result With ups.model : VAR eaton ups.model "Ellipse ECO 800"
26/08/2022 12:46:17 Pid: 49596 UPS_Device : Enter GetUPSVar
26/08/2022 12:46:17 Pid: 49596 UPS_Device : Process Result With ups.serial : VAR eaton ups.serial "000000000"
26/08/2022 12:46:17 Pid: 49596 UPS_Device : Enter GetUPSVar
26/08/2022 12:46:17 Pid: 49596 UPS_Device : Process Result With ups.firmware : VAR eaton ups.firmware "02"
26/08/2022 12:46:17 Pid: 49596 UPS_Device : Enter GetUPSVar
26/08/2022 12:46:17 Pid: 49596 UPS_Device : Apply Fallback Value when retrieving battery.capacity
26/08/2022 12:46:17 Pid: 49596 UPS_Device : Enter GetUPSVar
26/08/2022 12:46:17 Pid: 49596 UPS_Device : Process Result With output.frequency.nominal : VAR eaton output.frequency.nominal "50"

**Comment by gbakeman** [comment]
Hello,

This repository is no longer being updated. Please close your issue report here, and try the [latest pre-release](https://github.com/nutdotnet/WinNUT-Client/releases) from our new repository. I think this specific issue has been fixed, but let me know with a new report over there if you have any other problems.

**Comment by mann1x** [comment]
Thanks, I didn't know about this change!
