### ISSUE TITLE
Аpplication crashes when connection is lost. v2.1.7740.35837

### ISSUE THREAD

**Issue by drsmoll** [gawindx/WinNUT-Client#187]
If the Russian locale is set, the application crashes 25 seconds after the connection is lost  (when trying to reconnect) nut-server :

Exception type: System.ArgumentOutOfRangeException
Exception message: Длина текста должна быть меньше 64 символов.(The text length must be less than 64 characters.)
Имя параметра: Text
Фактическое значение было WinNUT-Client - 2.1
Переподключение в процессе
Попытка 8 из 30.
Exception stack trace: 
   в System.Windows.Forms.NotifyIcon.set_Text(String value)
   в WinNUT_Client.WinNUT.Event_UpdateNotifyIconStr(String Reason, String Message)
   в WinNUT_Client.WinNUT.NewRetry_NotifyIcon()
   в WinNUT_Client_Common.UPS_Device.New_RetryEventHandler.Invoke()
   в WinNUT_Client_Common.UPS_Device.Reconnect_Socket(Object sender, EventArgs e)
   в System.Windows.Forms.Timer.OnTick(EventArgs e)
   в System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by gbakeman** [comment]
Hi,

This repository is no longer maintained, and development has moved [here](https://github.com/nutdotnet/WinNUT-Client). Please try the latest release there, then open a new issue if the problem persists.

**Comment by drsmoll** [comment]
v2.3.8834 worked
