### ISSUE TITLE
Round the value of watts

### ISSUE THREAD

**Issue by Ririx02** [gawindx/WinNUT-Client#19]
Hello,
It's me again. 😁
Just a quick question, would it be possible to round the value "UPS load" in Watt to 2 digits max after the decimal point?
Sometimes, the value exceeds the frame (???, 333333333333333333333333333 or ???, 66666666666666666666666666666667).
Thank you.
Otherwise everything else is fine, good job! 👍
![exceeded characters](https://user-images.githubusercontent.com/18558767/85770138-e52a2a80-b71a-11ea-9eb2-8f2c32643c50.png)

**Comment by gawindx** [comment]
this is corrected and updated in 1.8.0.1.
If my update function works correctly, all you have to do is update, otherwise, you just have to get the exe in the Build directory

**Comment by Ririx02** [comment]
Perfect
Big thank
