### ISSUE TITLE
Automatic startup

### ISSUE THREAD

**Issue by jandari1** [gawindx/WinNUT-Client#31]
Now im having a bug that the application does not start up even enabled start up with windows. Its also visible in windows task managers start and its enabled. When I copy the link to start menus run folder it starts up normally. I also reinstalled and deleted all registry entries and folders before and no change.

I also suggest to remove tool tip Connected and leave only Energy status tool tips. Also suggest turning tool tips on and off option.

**Comment by gawindx** [comment]
I didn't have time to answer you but did you solve your problem?

For the notification suggestion, I note for a later update (in fact as soon as I have enough time to manage it)

**Comment by jandari1** [comment]
No. I copied link to startup folder in start menu, then it starts normally.

**Comment by gawindx** [comment]
To manage the automatic start, WinNUT creates an entry in the registry at the current user level.

is it possible that you have run WinNUT as admin or from another login?

look in the registry if you can find the key in question here:

HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run\

optionally, you can try to delete it manually (only the WinNUT key) and see if it works again correctly once recreated from the WinNUT preferences.

quick question in passing, does it have to do with a change of version of WinNUT? (I have not had any feedback in this direction but I prefer to rule out this hypothesis)

**Comment by jandari1** [comment]
I have checked. The key is added to registry, but it does not start up. My account is the only one on computer.

**Comment by gawindx** [comment]
A little up to know if you still encounter this problem or if we can close the issue.

**Comment by jandari1** [comment]
Seems to be fixed in new version it works as it should.

**Comment by gawindx** [comment]
ok, having never been able to reproduce a problem I could do nothing to solve it.

But the important thing is that it works.

I close the issue
