### ISSUE TITLE
GUI Not Indicating If Battery Is Charging

### ISSUE THREAD

**Issue by FileCity** [gawindx/WinNUT-Client#36]
It may be a good add-on to have a visual indication if the battery is actually charging.
Something can be indicated below the battery level gauge or somewhere else but needs to be seen easily.
It's weird to just see Online, with a battery level of 93% for example and not to have a currently charging indicator.
Thanks.

**Comment by gawindx** [comment]
I think that should not pose any particular problems to set up.
I will try to integrate this in the next version.

**Comment by FileCity** [comment]
Tested and working very well in all situations.
Icon is well located and informative.
Issue closed.
