### ISSUE TITLE
Windows can't shut down

### ISSUE THREAD

**Issue by benturnberg** [gawindx/WinNUT-Client#46]
Running WinNUT-Client v2.0.4.0, Windows 10.

Windows can't shut down when the specified threshold is reached (after the specified wait time) - it may be that the shutdown command is not being fed the "force" switch i.e. /f

See log and screenshot attached.
[WinNUT.txt](https://github.com/gawindx/WinNUT-Client/files/5651652/WinNUT.txt)
![Capture](https://user-images.githubusercontent.com/14046306/101331321-ed8cb100-38c7-11eb-955f-c5a24a5be4d1.JPG)

**Comment by gawindx** [comment]
The functionality is present in the new version, I close the issue but do not hesitate to reopen it if it does not correspond exactly or it can be improved.
