### ISSUE TITLE
Setup Triggering The Windows SmartScreen Protection

### ISSUE THREAD

**Issue by FileCity** [gawindx/WinNUT-Client#60]
This is just an annoyance, having the installer signed properly may fix the SmartScreen protection issue.

![Screenshot 2021-02-09 152532](https://user-images.githubusercontent.com/70494005/107424000-1a895a00-6aeb-11eb-828c-b46993e1aa6e.jpg)

Running: v2.0.7710.35866

**Comment by gawindx** [comment]
And since smartscreen is deactivated on my pc, I admit that I have not looked into this problem.

I don't promise to put it in place right away, but I'll start looking into it.
