### ISSUE TITLE
Password Still Visible In Settings

### ISSUE THREAD

**Issue by FileCity** [gawindx/WinNUT-Client#63]
NUT connection password is still visible in plain text in settings.
Registry is now encrypted and OK.

![Capture3](https://user-images.githubusercontent.com/70494005/107428691-07798880-6af1-11eb-9230-88bbb7657ab6.JPG)

Applying a "TextBox.PasswordChar Property" or similar to the entry box will solve this issue.
Seeing the standard bubble dots will add privacy to the application.
Username can be left visible.
This is not an issue for home users but if this app is installed on a server with remote desktop clients, this can be a security issue unless we hide and contain the app from being displayed and detected.

Running: v2.0.7710.35866

**Comment by gawindx** [comment]
Not false.
  I must admit that I did not even think about it, given that I did not develop it for such a use (basically it's just because I'm lazy to go look on my server if the UPS status is correct) ...
