### ISSUE TITLE
Settings Poll Delay Expressed In Milliseconds

### ISSUE THREAD

**Issue by FileCity** [gawindx/WinNUT-Client#64]
Poll delay in settings is still expressed in milliseconds, which is counter-intuitive.
As discussed, this should be in seconds to reflect NUT server behavior and to harmonize documentation.
Can be treated as low priority.
On a personal note, this box should be renamed as "Poll Interval" to reflect NUT server internal variables in CONF files.
We are used to this already and may be less confusing for some users.
Thanks.

**Comment by gawindx** [comment]
The new version is available:
[Winnut v 2.0.7721](https://github.com/gawindx/WinNUT-Client/releases/tag/v2.0.7721.35955)
