### ISSUE TITLE
[Translation] ru-RU Russian

### ISSUE THREAD

**Issue by valekrus** [gawindx/WinNUT-Client#65]
Language: ru-RU
Link to gist: https://gist.github.com/valekrus/18f5f69b114187f8359fa92ab3495e08

**Comment by gawindx** [comment]
The translation is taken into account and will be part of the next version.

Thanks for your contribution.

I will close when the version is available.

**Comment by gawindx** [comment]
The new version is available:
[Winnut v 2.0.7721](https://github.com/gawindx/WinNUT-Client/releases/tag/v2.0.7721.35955)
